version: '3.8'

services:
  postgres:
    container_name: movie_manager_postgres
    image: postgres:13
    env_file:
      - envs/prod.env
    volumes:
      - postgres_volume:/postgresql/data
    restart: unless-stopped

  django:
    container_name: movie_manager_django
    build: app
    env_file:
      - envs/prod.env
    volumes:
      - staticfiles_volume:/opt/app/staticfiles
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_server/configs:/etc/nginx/conf.d:ro
      - ./nginx_server/data:/data/:ro
      - staticfiles_volume:/opt/app/staticfiles:ro
    depends_on:
      - django
    ports:
      - "80:80"

  etl:
    container_name: movie_manager_etl
    build: etl
    env_file:
      - envs/prod.env
    depends_on:
      - django

  elastic-service:
    container_name: movie_manager_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - /elastic:/elastic
    restart: unless-stopped

  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  elastic_etl:
    container_name: movie_manager_elastic_etl
    build:
      context: .
      dockerfile: ELK_etl/Dockerfile
    depends_on:
      - postgres
    env_file:
      - envs/prod.env

  elastic_updated_by_table_pipeline_etl:
    container_name: elastic_updated_by_table_pipeline_etl
    build:
      context: .
      dockerfile: ELK_etl/UpdateByTablePipelineDockerfile
    depends_on:
      - postgres
    env_file:
      - envs/prod.env

volumes:
  postgres_volume:
  staticfiles_volume:
    driver: local
  cache:
    driver: local
