# Generated by Django 4.0.5 on 2022-09-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
