# Generated by Django 4.0.5 on 2022-09-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created',
            new_name='created_at',
        ),
    ]
