# Generated by Django 4.1.3 on 2022-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_filmwork_film_work_creation_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='modified',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
