# Generated by Django 4.1.3 on 2022-12-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_person_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='modified',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
